import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/Header";
import HexagonAnimation from "@/components/HexagonAnimation";
import styles from "./style.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={`${styles.wrapper} container`}>
          <Header />
          <HexagonAnimation />
          {children}
        </div>
      </body>
    </html>
  );
}

// STATE: store
// 1. onboarding step
// 2. swipe index
// 3. form: name & email

// COMPONENTS
// 4. onboarding container
// 5. steps: home, get started (swipe), form name, form email & finish
